package logika;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;

/**
 * @author FRS
 */
public class ApplicationWindow extends javax.swing.JFrame {
    
    /**
     * Application states
     */
    public static final int         STATE_MENU = 0;
    public static final int         STATE_SIMULATION = 1;
    public static final int         STATE_AUTHORS = 2;
    
    private javax.swing.JPanel simulationPane;
    
    /**
     * Creates new form ApplicationWindow
     */
    public ApplicationWindow() {
        initComponents();
        setResizable(false);
        addExitListener();
    }
    
    public ApplicationWindow(int stateId) {
        initComponents();
        setResizable(false);
        addExitListener();
        moveToState(stateId);
    }
    
    private void addExitListener(){
        
        setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
        WindowListener exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                closeApplication();
            }
        };
        addWindowListener(exitListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulationToolbar = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        programUtilitiesToolBar = new javax.swing.JToolBar();
        authorsToolBarButton = new javax.swing.JButton();
        exitToolBarButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        mainMenuPane = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        newSimulationButton = new javax.swing.JButton();
        authorsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        authorsPane = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newSimulationMenuButton = new javax.swing.JMenuItem();
        exitMenuButton = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        authorsMenuButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 350));

        simulationToolbar.setFloatable(false);
        simulationToolbar.setRollover(true);

        jButton1.setText("Main menu");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        simulationToolbar.add(jButton1);

        programUtilitiesToolBar.setFloatable(false);
        programUtilitiesToolBar.setRollover(true);

        authorsToolBarButton.setText("Authors");
        authorsToolBarButton.setFocusable(false);
        authorsToolBarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        authorsToolBarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        authorsToolBarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorsToolBarButtonActionPerformed(evt);
            }
        });
        programUtilitiesToolBar.add(authorsToolBarButton);

        exitToolBarButton.setText("Exit");
        exitToolBarButton.setFocusable(false);
        exitToolBarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitToolBarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitToolBarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitToolBarButtonActionPerformed(evt);
            }
        });
        programUtilitiesToolBar.add(exitToolBarButton);

        mainPanel.setLayout(new java.awt.CardLayout());

        mainMenuPane.setPreferredSize(new java.awt.Dimension(580, 300));

        title.setFont(new java.awt.Font("Open Sans Semibold", 0, 40)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Genetic algorithm");

        subtitle.setFont(new java.awt.Font("Open Sans Light", 0, 13)); // NOI18N
        subtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitle.setText("for finding roots of complex functions of several variables");
        subtitle.setToolTipText("");
        subtitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newSimulationButton.setText("New simulation");
        newSimulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSimulationButtonActionPerformed(evt);
            }
        });

        authorsButton.setText("Authors");
        authorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorsButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuPaneLayout = new javax.swing.GroupLayout(mainMenuPane);
        mainMenuPane.setLayout(mainMenuPaneLayout);
        mainMenuPaneLayout.setHorizontalGroup(
            mainMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newSimulationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(authorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPaneLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(mainMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117))
        );
        mainMenuPaneLayout.setVerticalGroup(
            mainMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPaneLayout.createSequentialGroup()
                .addGroup(mainMenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPaneLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPaneLayout.createSequentialGroup()
                        .addComponent(subtitle)
                        .addGap(18, 18, 18)))
                .addComponent(newSimulationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(authorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(mainMenuPane, "card2");

        authorsPane.setPreferredSize(new java.awt.Dimension(580, 300));

        title1.setFont(new java.awt.Font("Open Sans Semibold", 0, 40)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Authors");

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Beata Giełbaga");

        jLabel2.setFont(new java.awt.Font("Open Sans Light", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kamil Dawidów");

        jLabel3.setFont(new java.awt.Font("Open Sans Light", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jakub Freisler");

        javax.swing.GroupLayout authorsPaneLayout = new javax.swing.GroupLayout(authorsPane);
        authorsPane.setLayout(authorsPaneLayout);
        authorsPaneLayout.setHorizontalGroup(
            authorsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(authorsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addContainerGap())
        );
        authorsPaneLayout.setVerticalGroup(
            authorsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorsPaneLayout.createSequentialGroup()
                .addComponent(title1)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        mainPanel.add(authorsPane, "card2");

        fileMenu.setText("File");

        newSimulationMenuButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newSimulationMenuButton.setText("New simulation...");
        newSimulationMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSimulationMenuButtonActionPerformed(evt);
            }
        });
        newSimulationMenuButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newSimulationMenuButtonKeyPressed(evt);
            }
        });
        fileMenu.add(newSimulationMenuButton);

        exitMenuButton.setText("Exit");
        exitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuButtonActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuButton);

        mainMenuBar.add(fileMenu);

        helpMenu.setText("Help");

        authorsMenuButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        authorsMenuButton.setText("Authors");
        authorsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorsMenuButtonActionPerformed(evt);
            }
        });
        helpMenu.add(authorsMenuButton);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simulationToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(programUtilitiesToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(simulationToolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programUtilitiesToolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newSimulationMenuButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newSimulationMenuButtonKeyPressed
        newSimulation();
    }//GEN-LAST:event_newSimulationMenuButtonKeyPressed

    private void authorsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorsMenuButtonActionPerformed
        moveToState(STATE_AUTHORS);
    }//GEN-LAST:event_authorsMenuButtonActionPerformed

    private void authorsToolBarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorsToolBarButtonActionPerformed
       moveToState(STATE_AUTHORS);
    }//GEN-LAST:event_authorsToolBarButtonActionPerformed
    
   /*
    * Moves to the new simulation view
    */
    private void newSimulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSimulationButtonActionPerformed
        newSimulation();
    }//GEN-LAST:event_newSimulationButtonActionPerformed

    private void newSimulationMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSimulationMenuButtonActionPerformed
        newSimulation();
    }//GEN-LAST:event_newSimulationMenuButtonActionPerformed

    private void exitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuButtonActionPerformed
        closeApplication();
    }//GEN-LAST:event_exitMenuButtonActionPerformed

    private void exitToolBarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitToolBarButtonActionPerformed
        closeApplication();
    }//GEN-LAST:event_exitToolBarButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        closeApplication();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void authorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorsButtonActionPerformed
        moveToState(STATE_AUTHORS);
    }//GEN-LAST:event_authorsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        moveToState(STATE_MENU);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * closes application
     */
    private void closeApplication(){
        int confirm = JOptionPane.showOptionDialog(this,
                "Are You Sure to Close this Application?",
                "Exit Confirmation", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(confirm == JOptionPane.YES_OPTION)
            System.exit(0);
    }
    
    /**
     * 
     * STATES LOADING
     * 
     */
    
        /**
        * Loads desired application's state to `mainPanel` jPanel
        */
        private void moveToState(int stateId){
            switch(stateId){
                case STATE_SIMULATION:
                    moveToSimulation();
                    break;
                case STATE_AUTHORS:
                    moveToAuthors();
                    break;
                case STATE_MENU:
                default:
                    moveToMenu();
                    break;    
            }
            mainPanel.revalidate();
            mainPanel.repaint();
        }
        
        /**
         * Moves to main menu
         */
        private void moveToMenu(){
            mainPanel.removeAll();

            mainPanel.add(mainMenuPane);
        }
        
        /**
         * moves to simulation screen
         */
        private void moveToSimulation(){
            mainPanel.removeAll();

            mainPanel.add(simulationPane);
        }
        
        /**
         * moves to authors screen
         */
        private void moveToAuthors(){
            mainPanel.removeAll();

            mainPanel.add(authorsPane);
        }

    
    /**
     * creates new simulation
     */
    private void newSimulation(){
        simulationPane = new Simulation();
        moveToSimulation();
    }
    
    /**
     * saves simulation's parameters to previous file
     */
    private void saveSimulation(){
        // TODO: SAVE PARAMS
    }
    
    /**
     * saves simulation's parameters to new files
     */
    private void saveAsSimulation(){
        // TODO: SAVE PARAMS
    }
    
    /**
     * loads simulation's parameters from  file
     */
    private void loadSimulation(){
        // TODO: LOAD PARAMS
        moveToSimulation();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void showWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorsButton;
    private javax.swing.JMenuItem authorsMenuButton;
    private javax.swing.JPanel authorsPane;
    private javax.swing.JButton authorsToolBarButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitMenuButton;
    private javax.swing.JButton exitToolBarButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainMenuPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newSimulationButton;
    private javax.swing.JMenuItem newSimulationMenuButton;
    private javax.swing.JToolBar programUtilitiesToolBar;
    private javax.swing.JToolBar simulationToolbar;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
