/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logika;

import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class GenerationGraphic extends javax.swing.JPanel{

    /**
     * Creates new form GenerationGraphRepresentation
     * @param _generationNo (int) generation number
     * @param _numberOfSpecimens (int) number of all specimens in current generation
     * @param _specimensKilled (int) number of specimens from last generation that got killed
     * @param _specimensRatio (int) number of specimens born
     * @param _bestValue (int) value of best specimen in this generation
     */
    public GenerationGraphic(int _generationNo, int _numberOfSpecimens, int _specimensKilled, int _specimensRatio, double _bestValue) {
        initComponents();
        generationNumber.setText(Integer.toString(_generationNo));
        noOfSpecimens.setText(Integer.toString(_numberOfSpecimens));
        
        String _bestValueStr = Double.toString(_bestValue);
        
        if  (
                _bestValueStr.indexOf('E')!=-1
            ){
            _bestValueStr = Double.toString(Math.floor(Double.parseDouble(_bestValueStr.split("E")[0]) * 10000000) / 10000000) + "E" + _bestValueStr.split("E")[1];
        } else
            _bestValueStr = Double.toString(Math.floor(_bestValue * 1000000000) / 1000000000);
        
        bestValue.setText(_bestValueStr);
        
        setSize(160, 220);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainlLabel = new javax.swing.JLabel();
        generationNumber = new javax.swing.JLabel();
        noOfSpecimens = new javax.swing.JLabel();
        noOfSpecimensLabel = new javax.swing.JLabel();
        bestValue = new javax.swing.JLabel();
        bestValueLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(120, 160));
        setMinimumSize(new java.awt.Dimension(120, 160));
        setPreferredSize(new java.awt.Dimension(120, 160));

        mainlLabel.setFont(new java.awt.Font("Open Sans Light", 1, 14)); // NOI18N
        mainlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainlLabel.setText("Generation no.");
        mainlLabel.setToolTipText("Generation number");

        generationNumber.setFont(new java.awt.Font("Open Sans Semibold", 1, 36)); // NOI18N
        generationNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generationNumber.setText("1");
        generationNumber.setToolTipText("Generation number");

        noOfSpecimens.setFont(new java.awt.Font("Open Sans Light", 1, 12)); // NOI18N
        noOfSpecimens.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noOfSpecimens.setText("1");
        noOfSpecimens.setToolTipText("Number of specimens");

        noOfSpecimensLabel.setFont(new java.awt.Font("Open Sans Light", 0, 13)); // NOI18N
        noOfSpecimensLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noOfSpecimensLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logika/img/population.png"))); // NOI18N
        noOfSpecimensLabel.setToolTipText("Number of specimens");

        bestValue.setFont(new java.awt.Font("Open Sans Light", 1, 12)); // NOI18N
        bestValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bestValue.setText("0.05");
        bestValue.setToolTipText("The best specimen's function result");

        bestValueLabel.setFont(new java.awt.Font("Open Sans Semibold", 0, 24)); // NOI18N
        bestValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bestValueLabel.setText("=");
        bestValueLabel.setToolTipText("The best specimen's function result");
        bestValueLabel.setAlignmentX(0.5F);

        jButton1.setText("<html><p style=\"text-align:center\">Best<br>arguments</p></</html>");
        jButton1.setToolTipText("List of arguments of the best specimen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainlLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bestValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bestValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(noOfSpecimensLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noOfSpecimens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(mainlLabel)
                .addGap(1, 1, 1)
                .addComponent(generationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noOfSpecimensLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noOfSpecimens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bestValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bestValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestValue;
    private javax.swing.JLabel bestValueLabel;
    private javax.swing.JLabel generationNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mainlLabel;
    private javax.swing.JLabel noOfSpecimens;
    private javax.swing.JLabel noOfSpecimensLabel;
    // End of variables declaration//GEN-END:variables
}
